//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=desktop-k1mkj14;Initial Catalog=QuanLyCuaHangBanXeMay;Integrated Secu" +
            "rity=True")]
        public string QuanLyCuaHangBanXeMayConnectionString {
            get {
                return ((string)(this["QuanLyCuaHangBanXeMayConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=desktop-k1mkj14;Initial Catalog=QuanLyBanXeMay;Integrated Security=Tr" +
            "ue")]
        public string QuanLyBanXeMayConnectionString {
            get {
                return ((string)(this["QuanLyBanXeMayConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=desktop-ukr05m3;Initial Catalog=QuanLyBanXeMay;Integrated Security=Tr" +
            "ue")]
        public string QuanLyBanXeMayConnectionString1 {
            get {
                return ((string)(this["QuanLyBanXeMayConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=H71M28;Initial Catalog=QuanLyBanXeMay;Integrated Security=True")]
        public string QuanLyBanXeMayConnectionString2 {
            get {
                return ((string)(this["QuanLyBanXeMayConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-UKR05M3;Initial Catalog=PTUD_DHKTPM12A_DOAN_NHOM04;Integrated" +
            " Security=True")]
        public string PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString {
            get {
                return ((string)(this["PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=desktop-k1mkj14;Initial Catalog=PTUD_DHKTPM12A_DOAN_NHOM04;Integrated" +
            " Security=True")]
        public string PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString1 {
            get {
                return ((string)(this["PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=desktop-ukr05m3;Initial Catalog=PTUD_DHKTPM12A_DOAN_NHOM04;Integrated" +
            " Security=True")]
        public string PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString2 {
            get {
                return ((string)(this["PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=H71M30;Initial Catalog=PTUD_DHKTPM12A_DOAN_NHOM04;Integrated Security" +
            "=True")]
        public string PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString3 {
            get {
                return ((string)(this["PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=H52M41;Initial Catalog=PTUD_DHKTPM12A_DOAN_NHOM04;Integrated Security" +
            "=True")]
        public string PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString4 {
            get {
                return ((string)(this["PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=H71M22;Initial Catalog=PTUD_DHKTPM12A_DOAN_NHOM04;Integrated Security" +
            "=True")]
        public string PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString5 {
            get {
                return ((string)(this["PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=H51M38;Initial Catalog=PTUD_DHKTPM12A_DOAN_NHOM04;Integrated Security" +
            "=True")]
        public string PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString6 {
            get {
                return ((string)(this["PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=H73M10;Initial Catalog=PTUD_DHKTPM12A_DOAN_NHOM04;Integrated Security" +
            "=True")]
        public string PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString7 {
            get {
                return ((string)(this["PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString7"]));
            }
        }
    }
}
