#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PTUD_DHKTPM12A_DOAN_NHOM04")]
	public partial class CuaHangBanXeMayDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCT_HoaDon(CT_HoaDon instance);
    partial void UpdateCT_HoaDon(CT_HoaDon instance);
    partial void DeleteCT_HoaDon(CT_HoaDon instance);
    partial void InsertXe(Xe instance);
    partial void UpdateXe(Xe instance);
    partial void DeleteXe(Xe instance);
    partial void InsertCT_PhieuSua(CT_PhieuSua instance);
    partial void UpdateCT_PhieuSua(CT_PhieuSua instance);
    partial void DeleteCT_PhieuSua(CT_PhieuSua instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertHopDong(HopDong instance);
    partial void UpdateHopDong(HopDong instance);
    partial void DeleteHopDong(HopDong instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLinhKien(LinhKien instance);
    partial void UpdateLinhKien(LinhKien instance);
    partial void DeleteLinhKien(LinhKien instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertPhieuSuaBH(PhieuSuaBH instance);
    partial void UpdatePhieuSuaBH(PhieuSuaBH instance);
    partial void DeletePhieuSuaBH(PhieuSuaBH instance);
    partial void InsertPhieuTraGop(PhieuTraGop instance);
    partial void UpdatePhieuTraGop(PhieuTraGop instance);
    partial void DeletePhieuTraGop(PhieuTraGop instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public CuaHangBanXeMayDataContext() : 
				base(global::DAL.Properties.Settings.Default.PTUD_DHKTPM12A_DOAN_NHOM04ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public CuaHangBanXeMayDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CuaHangBanXeMayDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CuaHangBanXeMayDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CuaHangBanXeMayDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CT_HoaDon> CT_HoaDons
		{
			get
			{
				return this.GetTable<CT_HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<Xe> Xes
		{
			get
			{
				return this.GetTable<Xe>();
			}
		}
		
		public System.Data.Linq.Table<CT_PhieuSua> CT_PhieuSuas
		{
			get
			{
				return this.GetTable<CT_PhieuSua>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<HopDong> HopDongs
		{
			get
			{
				return this.GetTable<HopDong>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LinhKien> LinhKiens
		{
			get
			{
				return this.GetTable<LinhKien>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<PhieuSuaBH> PhieuSuaBHs
		{
			get
			{
				return this.GetTable<PhieuSuaBH>();
			}
		}
		
		public System.Data.Linq.Table<PhieuTraGop> PhieuTraGops
		{
			get
			{
				return this.GetTable<PhieuTraGop>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TK_TTHopDong")]
		public ISingleResult<TK_TTHopDongResult> TK_TTHopDong()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TK_TTHopDongResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TK_NVBanxe")]
		public ISingleResult<TK_NVBanxeResult> TK_NVBanxe()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TK_NVBanxeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TK_NVTheoNgay")]
		public ISingleResult<TK_NVTheoNgayResult> TK_NVTheoNgay([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaybd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaykt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ngaybd, ngaykt);
			return ((ISingleResult<TK_NVTheoNgayResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TK_TTTheoNgay")]
		public ISingleResult<TK_TTTheoNgayResult> TK_TTTheoNgay([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaybd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaykt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ngaybd, ngaykt);
			return ((ISingleResult<TK_TTTheoNgayResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_HoaDon")]
	public partial class CT_HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private string _MaHopDong;
		
		private string _MaXe;
		
		private string _TenXe;
		
		private System.Nullable<decimal> _Gia;
		
		private System.Nullable<decimal> _TienTT;
		
		private EntityRef<Xe> _Xe;
		
		private EntityRef<HoaDon> _HoaDon;
		
		private EntityRef<HopDong> _HopDong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnMaHopDongChanging(string value);
    partial void OnMaHopDongChanged();
    partial void OnMaXeChanging(string value);
    partial void OnMaXeChanged();
    partial void OnTenXeChanging(string value);
    partial void OnTenXeChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    partial void OnTienTTChanging(System.Nullable<decimal> value);
    partial void OnTienTTChanged();
    #endregion
		
		public CT_HoaDon()
		{
			this._Xe = default(EntityRef<Xe>);
			this._HoaDon = default(EntityRef<HoaDon>);
			this._HopDong = default(EntityRef<HopDong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					if (this._HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					if (this._HopDong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaXe
		{
			get
			{
				return this._MaXe;
			}
			set
			{
				if ((this._MaXe != value))
				{
					if (this._Xe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaXeChanging(value);
					this.SendPropertyChanging();
					this._MaXe = value;
					this.SendPropertyChanged("MaXe");
					this.OnMaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenXe", DbType="NVarChar(30)")]
		public string TenXe
		{
			get
			{
				return this._TenXe;
			}
			set
			{
				if ((this._TenXe != value))
				{
					this.OnTenXeChanging(value);
					this.SendPropertyChanging();
					this._TenXe = value;
					this.SendPropertyChanged("TenXe");
					this.OnTenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Money")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienTT", DbType="Money")]
		public System.Nullable<decimal> TienTT
		{
			get
			{
				return this._TienTT;
			}
			set
			{
				if ((this._TienTT != value))
				{
					this.OnTienTTChanging(value);
					this.SendPropertyChanging();
					this._TienTT = value;
					this.SendPropertyChanged("TienTT");
					this.OnTienTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_CT_HoaDon", Storage="_Xe", ThisKey="MaXe", OtherKey="MaXe", IsForeignKey=true)]
		public Xe Xe
		{
			get
			{
				return this._Xe.Entity;
			}
			set
			{
				Xe previousValue = this._Xe.Entity;
				if (((previousValue != value) 
							|| (this._Xe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Xe.Entity = null;
						previousValue.CT_HoaDons.Remove(this);
					}
					this._Xe.Entity = value;
					if ((value != null))
					{
						value.CT_HoaDons.Add(this);
						this._MaXe = value.MaXe;
					}
					else
					{
						this._MaXe = default(string);
					}
					this.SendPropertyChanged("Xe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_CT_HoaDon", Storage="_HoaDon", ThisKey="MaHoaDon", OtherKey="MaHoaDon", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.CT_HoaDons.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.CT_HoaDons.Add(this);
						this._MaHoaDon = value.MaHoaDon;
					}
					else
					{
						this._MaHoaDon = default(string);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_CT_HoaDon", Storage="_HopDong", ThisKey="MaHopDong", OtherKey="MaHopDong", IsForeignKey=true)]
		public HopDong HopDong
		{
			get
			{
				return this._HopDong.Entity;
			}
			set
			{
				HopDong previousValue = this._HopDong.Entity;
				if (((previousValue != value) 
							|| (this._HopDong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HopDong.Entity = null;
						previousValue.CT_HoaDons.Remove(this);
					}
					this._HopDong.Entity = value;
					if ((value != null))
					{
						value.CT_HoaDons.Add(this);
						this._MaHopDong = value.MaHopDong;
					}
					else
					{
						this._MaHopDong = default(string);
					}
					this.SendPropertyChanged("HopDong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xe")]
	public partial class Xe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaXe;
		
		private string _LoaiXe;
		
		private string _MauXe;
		
		private System.Nullable<decimal> _GiaXe;
		
		private string _NuocSX;
		
		private string _SoKhung;
		
		private string _SoSuon;
		
		private string _SoPK;
		
		private System.Nullable<bool> _TinhTrang;
		
		private string _TenXe;
		
		private EntitySet<CT_HoaDon> _CT_HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaXeChanging(string value);
    partial void OnMaXeChanged();
    partial void OnLoaiXeChanging(string value);
    partial void OnLoaiXeChanged();
    partial void OnMauXeChanging(string value);
    partial void OnMauXeChanged();
    partial void OnGiaXeChanging(System.Nullable<decimal> value);
    partial void OnGiaXeChanged();
    partial void OnNuocSXChanging(string value);
    partial void OnNuocSXChanged();
    partial void OnSoKhungChanging(string value);
    partial void OnSoKhungChanged();
    partial void OnSoSuonChanging(string value);
    partial void OnSoSuonChanged();
    partial void OnSoPKChanging(string value);
    partial void OnSoPKChanged();
    partial void OnTinhTrangChanging(System.Nullable<bool> value);
    partial void OnTinhTrangChanged();
    partial void OnTenXeChanging(string value);
    partial void OnTenXeChanged();
    #endregion
		
		public Xe()
		{
			this._CT_HoaDons = new EntitySet<CT_HoaDon>(new Action<CT_HoaDon>(this.attach_CT_HoaDons), new Action<CT_HoaDon>(this.detach_CT_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaXe
		{
			get
			{
				return this._MaXe;
			}
			set
			{
				if ((this._MaXe != value))
				{
					this.OnMaXeChanging(value);
					this.SendPropertyChanging();
					this._MaXe = value;
					this.SendPropertyChanged("MaXe");
					this.OnMaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiXe", DbType="NVarChar(30)")]
		public string LoaiXe
		{
			get
			{
				return this._LoaiXe;
			}
			set
			{
				if ((this._LoaiXe != value))
				{
					this.OnLoaiXeChanging(value);
					this.SendPropertyChanging();
					this._LoaiXe = value;
					this.SendPropertyChanged("LoaiXe");
					this.OnLoaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MauXe", DbType="NVarChar(30)")]
		public string MauXe
		{
			get
			{
				return this._MauXe;
			}
			set
			{
				if ((this._MauXe != value))
				{
					this.OnMauXeChanging(value);
					this.SendPropertyChanging();
					this._MauXe = value;
					this.SendPropertyChanged("MauXe");
					this.OnMauXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaXe", DbType="Money")]
		public System.Nullable<decimal> GiaXe
		{
			get
			{
				return this._GiaXe;
			}
			set
			{
				if ((this._GiaXe != value))
				{
					this.OnGiaXeChanging(value);
					this.SendPropertyChanging();
					this._GiaXe = value;
					this.SendPropertyChanged("GiaXe");
					this.OnGiaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NuocSX", DbType="NVarChar(30)")]
		public string NuocSX
		{
			get
			{
				return this._NuocSX;
			}
			set
			{
				if ((this._NuocSX != value))
				{
					this.OnNuocSXChanging(value);
					this.SendPropertyChanging();
					this._NuocSX = value;
					this.SendPropertyChanged("NuocSX");
					this.OnNuocSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoKhung", DbType="NVarChar(30)")]
		public string SoKhung
		{
			get
			{
				return this._SoKhung;
			}
			set
			{
				if ((this._SoKhung != value))
				{
					this.OnSoKhungChanging(value);
					this.SendPropertyChanging();
					this._SoKhung = value;
					this.SendPropertyChanged("SoKhung");
					this.OnSoKhungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoSuon", DbType="NVarChar(30)")]
		public string SoSuon
		{
			get
			{
				return this._SoSuon;
			}
			set
			{
				if ((this._SoSuon != value))
				{
					this.OnSoSuonChanging(value);
					this.SendPropertyChanging();
					this._SoSuon = value;
					this.SendPropertyChanged("SoSuon");
					this.OnSoSuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPK", DbType="NVarChar(30)")]
		public string SoPK
		{
			get
			{
				return this._SoPK;
			}
			set
			{
				if ((this._SoPK != value))
				{
					this.OnSoPKChanging(value);
					this.SendPropertyChanging();
					this._SoPK = value;
					this.SendPropertyChanged("SoPK");
					this.OnSoPKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit")]
		public System.Nullable<bool> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenXe", DbType="NVarChar(30)")]
		public string TenXe
		{
			get
			{
				return this._TenXe;
			}
			set
			{
				if ((this._TenXe != value))
				{
					this.OnTenXeChanging(value);
					this.SendPropertyChanging();
					this._TenXe = value;
					this.SendPropertyChanged("TenXe");
					this.OnTenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_CT_HoaDon", Storage="_CT_HoaDons", ThisKey="MaXe", OtherKey="MaXe")]
		public EntitySet<CT_HoaDon> CT_HoaDons
		{
			get
			{
				return this._CT_HoaDons;
			}
			set
			{
				this._CT_HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_HoaDons(CT_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Xe = this;
		}
		
		private void detach_CT_HoaDons(CT_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Xe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_PhieuSua")]
	public partial class CT_PhieuSua : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuSua;
		
		private string _MaLK;
		
		private string _TenLK;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _GiaTien;
		
		private string _MaCTPS;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private EntityRef<LinhKien> _LinhKien;
		
		private EntityRef<PhieuSuaBH> _PhieuSuaBH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuSuaChanging(string value);
    partial void OnMaPhieuSuaChanged();
    partial void OnMaLKChanging(string value);
    partial void OnMaLKChanged();
    partial void OnTenLKChanging(string value);
    partial void OnTenLKChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiaTienChanging(System.Nullable<decimal> value);
    partial void OnGiaTienChanged();
    partial void OnMaCTPSChanging(string value);
    partial void OnMaCTPSChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public CT_PhieuSua()
		{
			this._LinhKien = default(EntityRef<LinhKien>);
			this._PhieuSuaBH = default(EntityRef<PhieuSuaBH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuSua", DbType="NChar(10)")]
		public string MaPhieuSua
		{
			get
			{
				return this._MaPhieuSua;
			}
			set
			{
				if ((this._MaPhieuSua != value))
				{
					if (this._PhieuSuaBH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuSuaChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuSua = value;
					this.SendPropertyChanged("MaPhieuSua");
					this.OnMaPhieuSuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLK", DbType="NChar(5)")]
		public string MaLK
		{
			get
			{
				return this._MaLK;
			}
			set
			{
				if ((this._MaLK != value))
				{
					if (this._LinhKien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLKChanging(value);
					this.SendPropertyChanging();
					this._MaLK = value;
					this.SendPropertyChanged("MaLK");
					this.OnMaLKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLK", DbType="NVarChar(30)")]
		public string TenLK
		{
			get
			{
				return this._TenLK;
			}
			set
			{
				if ((this._TenLK != value))
				{
					this.OnTenLKChanging(value);
					this.SendPropertyChanging();
					this._TenLK = value;
					this.SendPropertyChanged("TenLK");
					this.OnTenLKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="Money")]
		public System.Nullable<decimal> GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTPS", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCTPS
		{
			get
			{
				return this._MaCTPS;
			}
			set
			{
				if ((this._MaCTPS != value))
				{
					this.OnMaCTPSChanging(value);
					this.SendPropertyChanging();
					this._MaCTPS = value;
					this.SendPropertyChanged("MaCTPS");
					this.OnMaCTPSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LinhKien_CT_PhieuSua", Storage="_LinhKien", ThisKey="MaLK", OtherKey="MaLK", IsForeignKey=true)]
		public LinhKien LinhKien
		{
			get
			{
				return this._LinhKien.Entity;
			}
			set
			{
				LinhKien previousValue = this._LinhKien.Entity;
				if (((previousValue != value) 
							|| (this._LinhKien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LinhKien.Entity = null;
						previousValue.CT_PhieuSuas.Remove(this);
					}
					this._LinhKien.Entity = value;
					if ((value != null))
					{
						value.CT_PhieuSuas.Add(this);
						this._MaLK = value.MaLK;
					}
					else
					{
						this._MaLK = default(string);
					}
					this.SendPropertyChanged("LinhKien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuSuaBH_CT_PhieuSua", Storage="_PhieuSuaBH", ThisKey="MaPhieuSua", OtherKey="MaPhieuSua", IsForeignKey=true)]
		public PhieuSuaBH PhieuSuaBH
		{
			get
			{
				return this._PhieuSuaBH.Entity;
			}
			set
			{
				PhieuSuaBH previousValue = this._PhieuSuaBH.Entity;
				if (((previousValue != value) 
							|| (this._PhieuSuaBH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuSuaBH.Entity = null;
						previousValue.CT_PhieuSuas.Remove(this);
					}
					this._PhieuSuaBH.Entity = value;
					if ((value != null))
					{
						value.CT_PhieuSuas.Add(this);
						this._MaPhieuSua = value.MaPhieuSua;
					}
					else
					{
						this._MaPhieuSua = default(string);
					}
					this.SendPropertyChanged("PhieuSuaBH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _MaNV;
		
		private System.Nullable<decimal> _TienThanhToan;
		
		private System.Nullable<decimal> _TongTien;
		
		private double _KhuyenMai;
		
		private string _TenNV;
		
		private string _SdtKH;
		
		private EntitySet<CT_HoaDon> _CT_HoaDons;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTienThanhToanChanging(System.Nullable<decimal> value);
    partial void OnTienThanhToanChanged();
    partial void OnTongTienChanging(System.Nullable<decimal> value);
    partial void OnTongTienChanged();
    partial void OnKhuyenMaiChanging(double value);
    partial void OnKhuyenMaiChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnSdtKHChanging(string value);
    partial void OnSdtKHChanged();
    #endregion
		
		public HoaDon()
		{
			this._CT_HoaDons = new EntitySet<CT_HoaDon>(new Action<CT_HoaDon>(this.attach_CT_HoaDons), new Action<CT_HoaDon>(this.detach_CT_HoaDons));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(30)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienThanhToan", DbType="Money")]
		public System.Nullable<decimal> TienThanhToan
		{
			get
			{
				return this._TienThanhToan;
			}
			set
			{
				if ((this._TienThanhToan != value))
				{
					this.OnTienThanhToanChanging(value);
					this.SendPropertyChanging();
					this._TienThanhToan = value;
					this.SendPropertyChanged("TienThanhToan");
					this.OnTienThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Money")]
		public System.Nullable<decimal> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuyenMai", DbType="Float NOT NULL")]
		public double KhuyenMai
		{
			get
			{
				return this._KhuyenMai;
			}
			set
			{
				if ((this._KhuyenMai != value))
				{
					this.OnKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._KhuyenMai = value;
					this.SendPropertyChanged("KhuyenMai");
					this.OnKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NChar(30)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SdtKH", DbType="NChar(12)")]
		public string SdtKH
		{
			get
			{
				return this._SdtKH;
			}
			set
			{
				if ((this._SdtKH != value))
				{
					this.OnSdtKHChanging(value);
					this.SendPropertyChanging();
					this._SdtKH = value;
					this.SendPropertyChanged("SdtKH");
					this.OnSdtKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_CT_HoaDon", Storage="_CT_HoaDons", ThisKey="MaHoaDon", OtherKey="MaHoaDon")]
		public EntitySet<CT_HoaDon> CT_HoaDons
		{
			get
			{
				return this._CT_HoaDons;
			}
			set
			{
				this._CT_HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_HoaDons(CT_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_CT_HoaDons(CT_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HopDong")]
	public partial class HopDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHopDong;
		
		private string _TenXe;
		
		private System.Nullable<decimal> _Gia;
		
		private System.Nullable<System.DateTime> _HanBH;
		
		private int _HinhThucTT;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private string _TenKH;
		
		private string _TinhTrang;
		
		private string _DiaChi;
		
		private string _MaKH;
		
		private string _TenNV;
		
		private EntitySet<CT_HoaDon> _CT_HoaDons;
		
		private EntitySet<PhieuSuaBH> _PhieuSuaBHs;
		
		private EntitySet<PhieuTraGop> _PhieuTraGops;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHopDongChanging(string value);
    partial void OnMaHopDongChanged();
    partial void OnTenXeChanging(string value);
    partial void OnTenXeChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    partial void OnHanBHChanging(System.Nullable<System.DateTime> value);
    partial void OnHanBHChanged();
    partial void OnHinhThucTTChanging(int value);
    partial void OnHinhThucTTChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    #endregion
		
		public HopDong()
		{
			this._CT_HoaDons = new EntitySet<CT_HoaDon>(new Action<CT_HoaDon>(this.attach_CT_HoaDons), new Action<CT_HoaDon>(this.detach_CT_HoaDons));
			this._PhieuSuaBHs = new EntitySet<PhieuSuaBH>(new Action<PhieuSuaBH>(this.attach_PhieuSuaBHs), new Action<PhieuSuaBH>(this.detach_PhieuSuaBHs));
			this._PhieuTraGops = new EntitySet<PhieuTraGop>(new Action<PhieuTraGop>(this.attach_PhieuTraGops), new Action<PhieuTraGop>(this.detach_PhieuTraGops));
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenXe", DbType="NVarChar(30)")]
		public string TenXe
		{
			get
			{
				return this._TenXe;
			}
			set
			{
				if ((this._TenXe != value))
				{
					this.OnTenXeChanging(value);
					this.SendPropertyChanging();
					this._TenXe = value;
					this.SendPropertyChanged("TenXe");
					this.OnTenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Money")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanBH", DbType="Date")]
		public System.Nullable<System.DateTime> HanBH
		{
			get
			{
				return this._HanBH;
			}
			set
			{
				if ((this._HanBH != value))
				{
					this.OnHanBHChanging(value);
					this.SendPropertyChanging();
					this._HanBH = value;
					this.SendPropertyChanged("HanBH");
					this.OnHanBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucTT", DbType="Int NOT NULL")]
		public int HinhThucTT
		{
			get
			{
				return this._HinhThucTT;
			}
			set
			{
				if ((this._HinhThucTT != value))
				{
					this.OnHinhThucTTChanging(value);
					this.SendPropertyChanging();
					this._HinhThucTT = value;
					this.SendPropertyChanged("HinhThucTT");
					this.OnHinhThucTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(30)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(30)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(30)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_CT_HoaDon", Storage="_CT_HoaDons", ThisKey="MaHopDong", OtherKey="MaHopDong")]
		public EntitySet<CT_HoaDon> CT_HoaDons
		{
			get
			{
				return this._CT_HoaDons;
			}
			set
			{
				this._CT_HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_PhieuSuaBH", Storage="_PhieuSuaBHs", ThisKey="MaHopDong", OtherKey="MaHopDong")]
		public EntitySet<PhieuSuaBH> PhieuSuaBHs
		{
			get
			{
				return this._PhieuSuaBHs;
			}
			set
			{
				this._PhieuSuaBHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_PhieuTraGop", Storage="_PhieuTraGops", ThisKey="MaHopDong", OtherKey="MaHopDong")]
		public EntitySet<PhieuTraGop> PhieuTraGops
		{
			get
			{
				return this._PhieuTraGops;
			}
			set
			{
				this._PhieuTraGops.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HopDong", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HopDongs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HopDongs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_HoaDons(CT_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = this;
		}
		
		private void detach_CT_HoaDons(CT_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = null;
		}
		
		private void attach_PhieuSuaBHs(PhieuSuaBH entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = this;
		}
		
		private void detach_PhieuSuaBHs(PhieuSuaBH entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = null;
		}
		
		private void attach_PhieuTraGops(PhieuTraGop entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = this;
		}
		
		private void detach_PhieuTraGops(PhieuTraGop entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<HopDong> _HopDongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public KhachHang()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._HopDongs = new EntitySet<HopDong>(new Action<HopDong>(this.attach_HopDongs), new Action<HopDong>(this.detach_HopDongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(30)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NChar(12)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_HoaDons", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HopDong", Storage="_HopDongs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<HopDong> HopDongs
		{
			get
			{
				return this._HopDongs;
			}
			set
			{
				this._HopDongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LinhKien")]
	public partial class LinhKien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLK;
		
		private string _TenLK;
		
		private string _Loai;
		
		private System.Nullable<decimal> _GiaTien;
		
		private EntitySet<CT_PhieuSua> _CT_PhieuSuas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLKChanging(string value);
    partial void OnMaLKChanged();
    partial void OnTenLKChanging(string value);
    partial void OnTenLKChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnGiaTienChanging(System.Nullable<decimal> value);
    partial void OnGiaTienChanged();
    #endregion
		
		public LinhKien()
		{
			this._CT_PhieuSuas = new EntitySet<CT_PhieuSua>(new Action<CT_PhieuSua>(this.attach_CT_PhieuSuas), new Action<CT_PhieuSua>(this.detach_CT_PhieuSuas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLK", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLK
		{
			get
			{
				return this._MaLK;
			}
			set
			{
				if ((this._MaLK != value))
				{
					this.OnMaLKChanging(value);
					this.SendPropertyChanging();
					this._MaLK = value;
					this.SendPropertyChanged("MaLK");
					this.OnMaLKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLK", DbType="NVarChar(30)")]
		public string TenLK
		{
			get
			{
				return this._TenLK;
			}
			set
			{
				if ((this._TenLK != value))
				{
					this.OnTenLKChanging(value);
					this.SendPropertyChanging();
					this._TenLK = value;
					this.SendPropertyChanged("TenLK");
					this.OnTenLKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(30)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="Money")]
		public System.Nullable<decimal> GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LinhKien_CT_PhieuSua", Storage="_CT_PhieuSuas", ThisKey="MaLK", OtherKey="MaLK")]
		public EntitySet<CT_PhieuSua> CT_PhieuSuas
		{
			get
			{
				return this._CT_PhieuSuas;
			}
			set
			{
				this._CT_PhieuSuas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_PhieuSuas(CT_PhieuSua entity)
		{
			this.SendPropertyChanging();
			entity.LinhKien = this;
		}
		
		private void detach_CT_PhieuSuas(CT_PhieuSua entity)
		{
			this.SendPropertyChanging();
			entity.LinhKien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenNV;
		
		private string _SDT;
		
		private string _CaLam;
		
		private string _ChucVu;
		
		private string _DiaChi;
		
		private string _CMND;
		
		private System.Nullable<bool> _TinhTrang;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<PhieuSuaBH> _PhieuSuaBHs;
		
		private EntitySet<PhieuTraGop> _PhieuTraGops;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnCaLamChanging(string value);
    partial void OnCaLamChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnTinhTrangChanging(System.Nullable<bool> value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public NhanVien()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._PhieuSuaBHs = new EntitySet<PhieuSuaBH>(new Action<PhieuSuaBH>(this.attach_PhieuSuaBHs), new Action<PhieuSuaBH>(this.detach_PhieuSuaBHs));
			this._PhieuTraGops = new EntitySet<PhieuTraGop>(new Action<PhieuTraGop>(this.attach_PhieuTraGops), new Action<PhieuTraGop>(this.detach_PhieuTraGops));
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(30)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NChar(12)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaLam", DbType="NChar(10)")]
		public string CaLam
		{
			get
			{
				return this._CaLam;
			}
			set
			{
				if ((this._CaLam != value))
				{
					this.OnCaLamChanging(value);
					this.SendPropertyChanging();
					this._CaLam = value;
					this.SendPropertyChanged("CaLam");
					this.OnCaLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NChar(2)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(30)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NChar(12)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit")]
		public System.Nullable<bool> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_HoaDons", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuSuaBH", Storage="_PhieuSuaBHs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<PhieuSuaBH> PhieuSuaBHs
		{
			get
			{
				return this._PhieuSuaBHs;
			}
			set
			{
				this._PhieuSuaBHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuTraGop", Storage="_PhieuTraGops", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<PhieuTraGop> PhieuTraGops
		{
			get
			{
				return this._PhieuTraGops;
			}
			set
			{
				this._PhieuTraGops.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_TaiKhoan", ThisKey="MaNV", OtherKey="MaNV", IsUnique=true, IsForeignKey=false)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.NhanVien = null;
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.NhanVien = this;
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_PhieuSuaBHs(PhieuSuaBH entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_PhieuSuaBHs(PhieuSuaBH entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_PhieuTraGops(PhieuTraGop entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_PhieuTraGops(PhieuTraGop entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuSuaBH")]
	public partial class PhieuSuaBH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuSua;
		
		private System.Nullable<bool> _LoiDoKhachHaySP;
		
		private string _MaHopDong;
		
		private string _MaNV;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private string _TenNV;
		
		private System.Nullable<decimal> _TongTien;
		
		private EntitySet<CT_PhieuSua> _CT_PhieuSuas;
		
		private EntityRef<HopDong> _HopDong;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuSuaChanging(string value);
    partial void OnMaPhieuSuaChanged();
    partial void OnLoiDoKhachHaySPChanging(System.Nullable<bool> value);
    partial void OnLoiDoKhachHaySPChanged();
    partial void OnMaHopDongChanging(string value);
    partial void OnMaHopDongChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnTongTienChanging(System.Nullable<decimal> value);
    partial void OnTongTienChanged();
    #endregion
		
		public PhieuSuaBH()
		{
			this._CT_PhieuSuas = new EntitySet<CT_PhieuSua>(new Action<CT_PhieuSua>(this.attach_CT_PhieuSuas), new Action<CT_PhieuSua>(this.detach_CT_PhieuSuas));
			this._HopDong = default(EntityRef<HopDong>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuSua", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuSua
		{
			get
			{
				return this._MaPhieuSua;
			}
			set
			{
				if ((this._MaPhieuSua != value))
				{
					this.OnMaPhieuSuaChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuSua = value;
					this.SendPropertyChanged("MaPhieuSua");
					this.OnMaPhieuSuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoiDoKhachHaySP", DbType="Bit")]
		public System.Nullable<bool> LoiDoKhachHaySP
		{
			get
			{
				return this._LoiDoKhachHaySP;
			}
			set
			{
				if ((this._LoiDoKhachHaySP != value))
				{
					this.OnLoiDoKhachHaySPChanging(value);
					this.SendPropertyChanging();
					this._LoiDoKhachHaySP = value;
					this.SendPropertyChanged("LoiDoKhachHaySP");
					this.OnLoiDoKhachHaySPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					if (this._HopDong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(30)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Money")]
		public System.Nullable<decimal> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuSuaBH_CT_PhieuSua", Storage="_CT_PhieuSuas", ThisKey="MaPhieuSua", OtherKey="MaPhieuSua")]
		public EntitySet<CT_PhieuSua> CT_PhieuSuas
		{
			get
			{
				return this._CT_PhieuSuas;
			}
			set
			{
				this._CT_PhieuSuas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_PhieuSuaBH", Storage="_HopDong", ThisKey="MaHopDong", OtherKey="MaHopDong", IsForeignKey=true)]
		public HopDong HopDong
		{
			get
			{
				return this._HopDong.Entity;
			}
			set
			{
				HopDong previousValue = this._HopDong.Entity;
				if (((previousValue != value) 
							|| (this._HopDong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HopDong.Entity = null;
						previousValue.PhieuSuaBHs.Remove(this);
					}
					this._HopDong.Entity = value;
					if ((value != null))
					{
						value.PhieuSuaBHs.Add(this);
						this._MaHopDong = value.MaHopDong;
					}
					else
					{
						this._MaHopDong = default(string);
					}
					this.SendPropertyChanged("HopDong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuSuaBH", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.PhieuSuaBHs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.PhieuSuaBHs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_PhieuSuas(CT_PhieuSua entity)
		{
			this.SendPropertyChanging();
			entity.PhieuSuaBH = this;
		}
		
		private void detach_CT_PhieuSuas(CT_PhieuSua entity)
		{
			this.SendPropertyChanging();
			entity.PhieuSuaBH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuTraGop")]
	public partial class PhieuTraGop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHopDong;
		
		private int _LanTra;
		
		private System.Nullable<System.DateTime> _NgayTra;
		
		private string _NhanVienNhan;
		
		private System.Nullable<decimal> _SoTienTG;
		
		private string _TenNguoiTra;
		
		private string _MaNV;
		
		private EntityRef<HopDong> _HopDong;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHopDongChanging(string value);
    partial void OnMaHopDongChanged();
    partial void OnLanTraChanging(int value);
    partial void OnLanTraChanged();
    partial void OnNgayTraChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTraChanged();
    partial void OnNhanVienNhanChanging(string value);
    partial void OnNhanVienNhanChanged();
    partial void OnSoTienTGChanging(System.Nullable<decimal> value);
    partial void OnSoTienTGChanged();
    partial void OnTenNguoiTraChanging(string value);
    partial void OnTenNguoiTraChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public PhieuTraGop()
		{
			this._HopDong = default(EntityRef<HopDong>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					if (this._HopDong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanTra", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LanTra
		{
			get
			{
				return this._LanTra;
			}
			set
			{
				if ((this._LanTra != value))
				{
					this.OnLanTraChanging(value);
					this.SendPropertyChanging();
					this._LanTra = value;
					this.SendPropertyChanged("LanTra");
					this.OnLanTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTra", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTra
		{
			get
			{
				return this._NgayTra;
			}
			set
			{
				if ((this._NgayTra != value))
				{
					this.OnNgayTraChanging(value);
					this.SendPropertyChanging();
					this._NgayTra = value;
					this.SendPropertyChanged("NgayTra");
					this.OnNgayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienNhan", DbType="NVarChar(30)")]
		public string NhanVienNhan
		{
			get
			{
				return this._NhanVienNhan;
			}
			set
			{
				if ((this._NhanVienNhan != value))
				{
					this.OnNhanVienNhanChanging(value);
					this.SendPropertyChanging();
					this._NhanVienNhan = value;
					this.SendPropertyChanged("NhanVienNhan");
					this.OnNhanVienNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienTG", DbType="Money")]
		public System.Nullable<decimal> SoTienTG
		{
			get
			{
				return this._SoTienTG;
			}
			set
			{
				if ((this._SoTienTG != value))
				{
					this.OnSoTienTGChanging(value);
					this.SendPropertyChanging();
					this._SoTienTG = value;
					this.SendPropertyChanged("SoTienTG");
					this.OnSoTienTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiTra", DbType="NVarChar(30)")]
		public string TenNguoiTra
		{
			get
			{
				return this._TenNguoiTra;
			}
			set
			{
				if ((this._TenNguoiTra != value))
				{
					this.OnTenNguoiTraChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiTra = value;
					this.SendPropertyChanged("TenNguoiTra");
					this.OnTenNguoiTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_PhieuTraGop", Storage="_HopDong", ThisKey="MaHopDong", OtherKey="MaHopDong", IsForeignKey=true)]
		public HopDong HopDong
		{
			get
			{
				return this._HopDong.Entity;
			}
			set
			{
				HopDong previousValue = this._HopDong.Entity;
				if (((previousValue != value) 
							|| (this._HopDong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HopDong.Entity = null;
						previousValue.PhieuTraGops.Remove(this);
					}
					this._HopDong.Entity = value;
					if ((value != null))
					{
						value.PhieuTraGops.Add(this);
						this._MaHopDong = value.MaHopDong;
					}
					else
					{
						this._MaHopDong = default(string);
					}
					this.SendPropertyChanged("HopDong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuTraGop", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.PhieuTraGops.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.PhieuTraGops.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenTK;
		
		private string _MatKhau;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenTKChanging(string value);
    partial void OnTenTKChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTK", DbType="NVarChar(30)")]
		public string TenTK
		{
			get
			{
				return this._TenTK;
			}
			set
			{
				if ((this._TenTK != value))
				{
					this.OnTenTKChanging(value);
					this.SendPropertyChanging();
					this._TenTK = value;
					this.SendPropertyChanged("TenTK");
					this.OnTenTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(30)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.TaiKhoan = null;
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoan = this;
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class TK_TTHopDongResult
	{
		
		private string _TinhTrang;
		
		private System.Nullable<int> _SoHopdong;
		
		public TK_TTHopDongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(30)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this._TinhTrang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHopdong", DbType="Int")]
		public System.Nullable<int> SoHopdong
		{
			get
			{
				return this._SoHopdong;
			}
			set
			{
				if ((this._SoHopdong != value))
				{
					this._SoHopdong = value;
				}
			}
		}
	}
	
	public partial class TK_NVBanxeResult
	{
		
		private string _TenNV;
		
		private System.Nullable<int> _SOCHIEC;
		
		public TK_NVBanxeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(30)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this._TenNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCHIEC", DbType="Int")]
		public System.Nullable<int> SOCHIEC
		{
			get
			{
				return this._SOCHIEC;
			}
			set
			{
				if ((this._SOCHIEC != value))
				{
					this._SOCHIEC = value;
				}
			}
		}
	}
	
	public partial class TK_NVTheoNgayResult
	{
		
		private string _TenNV;
		
		private System.Nullable<int> _SOCHIEC;
		
		public TK_NVTheoNgayResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(30)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this._TenNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCHIEC", DbType="Int")]
		public System.Nullable<int> SOCHIEC
		{
			get
			{
				return this._SOCHIEC;
			}
			set
			{
				if ((this._SOCHIEC != value))
				{
					this._SOCHIEC = value;
				}
			}
		}
	}
	
	public partial class TK_TTTheoNgayResult
	{
		
		private string _TinhTrang;
		
		private System.Nullable<int> _SoHopDong;
		
		public TK_TTTheoNgayResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(30)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this._TinhTrang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHopDong", DbType="Int")]
		public System.Nullable<int> SoHopDong
		{
			get
			{
				return this._SoHopDong;
			}
			set
			{
				if ((this._SoHopDong != value))
				{
					this._SoHopDong = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
